### ISSUE TITLE
Set SSH_ENABLE_ROOT to unlock the account.

### ISSUE THREAD

**Issue by saxobroko** [aleksasiriski/jellyfin-rffmpeg#1]
Im trying to follow all these steps and I've been led to this point. I have docker on one machine with the worker but I can't get the keys from my jellyfin on the other machine because it asks for a password, ssh enable root is the only thing i think could fix the issue but I have no idea where to set enable root, I tried an environment variable but that doesn't seem to be the place.

**Comment by aleksasiriski** [comment]
SSH_ENABLE_ROOT in env var for the worker only, seen [here](https://github.com/aleksasiriski/rffmpeg-worker/blob/main/docker-compose.example.yml#L7)_

you must manually copy PUBLIC ssh key from the `jellyfin-rffmpeg` container, it's located in `/config/rffmpeg/.ssh/id_ed25519.pub` to your worker and mount to `/etc/authorized_keys/root` as a file (`root` here is not a folder)

**Comment by saxobroko** [comment]
Alright that worked but now it’s asking for a password when copying the authorised key over, I think I might be missing a step to generate the key pair


On Tuesday, March 14, 2023, 04:19, Aleksa Siriški ***@***.***> wrote:




SSH_ENABLE_ROOT in env var for the worker only, seen here_

you must manually copy PUBLIC ssh key from the jellyfin-rffmpeg container, it's located in /config/rffmpeg/.ssh/id_ed25519.pub to your worker and mount to /etc/authorized_keys/root as a file (root here is not a folder)

**Comment by saxobroko** [comment]
I'm using the jellyfin-rffmpeg container along with the worker docker however when i do `sudo docker exec -it jellyfin-rffmpeg ssh-copy-id -i /config/id_ed25519.pub root@IP.IP.IP.IP`

 it shows 

`/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/config/id_ed25519.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@IP.IP.IP.IP's password:`

However there is no password, but every other command after is working fine, but transcoding isn't working because it obviously hasn't been authenticated yet. For more info i'm doing these commands from the jellyfin-rffmpeg docker, and it is asking for the password of the rffmpeg-worker

**Comment by aleksasiriski** [comment]
By default, the worker docker image is configured to disallow password login and it doesn't have a password set. In turn, that means you can't use `ssh-copy-id`.

You will have to `cat` or `less` your public ssh key from jellyfin-rffmpeg and then make the aforementioned `root` file with thrt public key as contents.

I will look into adding another ENV VAR to enable password login and to change the password, but I woulhn't recommend that unless it's in a private network.
